packages:
  - packages/*
  - examples/*

catalogs:
  build:
    "@rollup/pluginutils": ^5.3.0
    chokidar: ^4.0.3
    esbuild: ^0.25.10
    fast-glob: ^3.3.3
    rolldown: ^1.0.0-beta.41
    tsdown: ^0.15.5
    tsup: ^8.5.0
    typescript: ^5.9.2
    vite: 7.1.7
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-packagejson: ^2.5.19
  lint:
    "@eslint/eslintrc": ^3.3.1
    "@eslint/js": ^9.36.0
    eslint: ^9.36.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    jiti: ^2.6.0
    typescript-eslint: ^8.44.1
  prod:
    csstype: ^3.1.3
    postcss: ^8.5.6
  script:
    taze: ^19.7.0
    concurrently: "^9.2.1"
  test:
    "@playwright/test": ^1.55.1
    "@vitest/browser": ^3.2.4
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: 3.2.4
  types:
    "@types/node": ^22.18.6
  utils:
    vite-bundle-analyzer: ^1.2.3

ignoredBuiltDependencies:
  - esbuild
