packages:
  - config/*
  - packages/*
  - examples/*

catalogs:
  build:
    "@rollup/pluginutils": ^5.3.0
    chokidar: ^4.0.3
    esbuild: ^0.25.12
    fast-glob: ^3.3.3
    rolldown: ^1.0.0-rc.2
    tsdown: ^0.15.12
    typescript: ^5.9.3
    vite: ^7.3.1
  docs:
    "@fontsource/ibm-plex-mono": ^5.2.7
    "@fortawesome/fontawesome-svg-core": ^6.7.2
    "@fortawesome/free-brands-svg-icons": ^6.7.2
    "@fortawesome/free-solid-svg-icons": ^6.7.2
    astro: ^5.17.1
    cssnano: ^7.1.2
    include-media: ^2.0.0
    sanitize.css: ^13.0.0
    sharp: ^0.34.5
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.8.1
    prettier-plugin-packagejson: ^2.5.22
  lint:
    "@eslint/eslintrc": ^3.3.3
    "@eslint/js": ^9.39.2
    eslint: ^9.39.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    jiti: ^2.6.1
    typescript-eslint: ^8.54.0
  prod:
    "@emotion/hash": ^0.9.2
    csstype: ^3.2.3
    postcss: ^8.5.6
  script:
    concurrently: ^9.2.1
    taze: ^19.9.2
    tinyexec: ^1.0.2
  test:
    "@playwright/test": ^1.58.1
    "@vitest/browser": ^3.2.4
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    vitest: 3.2.4
  types:
    "@types/node": ^24.10.9
  utils:
    vite-bundle-analyzer: ^1.3.2
    "relizy": "^0.2.8"

ignoredBuiltDependencies:
  - esbuild
  - sharp
