import { createFilter } from '@rollup/pluginutils';
import type { OutputChunk } from 'rolldown';
import { build } from 'rolldown';

export interface CompileOptions {
  inputPath: string;
  cwd: string;
  include?: string | string[];
  exclude?: string | string[];
}

export interface CompileResult {
  /* The generated CSS output */
  css: string;
  /* The transformed JavaScript with preserved exports */
  js: string;
  dependencies: string[];
}

export default async function compile(options: CompileOptions): Promise<CompileResult> {
  const { inputPath, cwd, include, exclude } = options;

  const filter = createFilter(include, exclude);

  const buildRes = await build({
    input: inputPath,
    cwd,
    write: false,
    output: {
      exports: 'named',
    },
    plugins: [
      {
        name: 'surimi:compiler-transform',
        transform(code, id) {
          if (filter(id)) {
            // Add CSS generation but don't interfere with existing exports
            // This allows the vite plugin to handle proper export processing
            const finalCode = `${code}\n
// Auto-generated by surimi compiler - generates CSS
export const __SURIMI_GENERATED_CSS__ = s.build();\n
// This is replaced by the default export to maintain compatibility
export default __SURIMI_GENERATED_CSS__;\n`;
            return finalCode;
          }
          return null;
        },
      },
    ],
  });

  const output = buildRes.output[0];
  const { css, js } = await execute(output.code);

  // Extract all imported modules as watch files
  const watchFiles = getModuleDependencies(output);

  return {
    css,
    js,
    dependencies: [...new Set(watchFiles)],
  };
}

async function execute(code: string): Promise<{ css: string; js: string }> {
  try {
    const dataUrl = `data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
    const module = (await import(dataUrl)) as Record<string, unknown>;

    // Get the generated CSS
    const cssValue = module.__SURIMI_GENERATED_CSS__ ?? module.default ?? '';
    const css = typeof cssValue === 'string' ? cssValue : '';

    // Collect all exports except the special CSS export and default
    const exports: string[] = [];
    for (const [key, value] of Object.entries(module)) {
      if (key !== 'default' && key !== '__SURIMI_GENERATED_CSS__') {
        // Handle Surimi selector classes specially
        if (value && typeof value === 'object' && 'toString' in value && 'toSelector' in value) {
          // This is a ClassSelector or IdSelector - export the raw name (toString())
          const stringValue = (value as { toString(): string }).toString();
          exports.push(`export const ${key} = ${JSON.stringify(stringValue)};`);
        } else if (typeof value === 'string') {
          // Regular string export
          exports.push(`export const ${key} = ${JSON.stringify(value)};`);
        } else if (typeof value === 'object' && value !== null) {
          // Other object exports (like theme objects)
          exports.push(`export const ${key} = ${JSON.stringify(value)};`);
        } else {
          // Fallback for other types
          exports.push(`export const ${key} = ${JSON.stringify(String(value))};`);
        }
      }
    }

    // Generate the transformed JS
    const js =
      exports.length > 0
        ? `// Auto-generated by @surimi/compiler: Surimi runtime removed, exports preserved\n\n${exports.join('\n')}\n`
        : '// Auto-generated by @surimi/compiler: No exports found\nexport {};\n';

    return { css, js };
  } catch (error) {
    console.error('Error executing Surimi code:', error);
    throw error;
  }
}
function getModuleDependencies(module: OutputChunk): string[] {
  const watchFiles: string[] = [];

  // Add the main input file
  // watchFiles.push(module.fileName);

  // Add all imports from the rolldown output
  if (module.imports.length > 0) {
    watchFiles.push(...module.imports);
  }

  // Add dynamic imports if any
  if (module.dynamicImports.length > 0) {
    watchFiles.push(...module.dynamicImports);
  }

  if ('modules' in module && Object.keys(module.modules).length > 0) {
    for (const moduleId of Object.keys(module.modules)) {
      if (!moduleId.includes('node_modules')) {
        if (moduleId.includes('rolldown:runtime')) continue;

        watchFiles.push(moduleId);
      }
    }
  }

  return watchFiles;
}
