/** Constants used throughout the compiler package */

// Package and module names
export const SURIMI_PACKAGE_NAME = 'surimi';
export const SURIMI_INSTANCE_VAR = '__surimi__instance__';
export const SURIMI_CSS_EXPORT_NAME = '__SURIMI_GENERATED_CSS__';
export const DEFAULT_EXPORT_KEY = 'default';

// Plugin configuration
export const COMPILER_PLUGIN_NAME = 'surimi:compiler-transform';

// Data URL configuration
export const DATA_URL_PREFIX = 'data:text/javascript;base64,';
export const DATA_URL_ERROR_PATTERN = 'from "data:';
export const DATA_URL_ERROR_REPLACEMENT = '<surimi-module>';

// Error messages
export const ERROR_BUILD_FAILED = 'Failed to build surimi output:';

// JS output templates
export const JS_HEADER_WITH_EXPORTS = '// Auto-generated by @surimi/compiler: Surimi runtime removed, exports preserved\n\n';
export const JS_NO_EXPORTS = '// Auto-generated by @surimi/compiler: No exports found\nexport {};\n';

// Dependency filtering patterns
export const NODE_MODULES_PATTERN = 'node_modules';
export const ROLLDOWN_RUNTIME_PATTERN = 'rolldown:runtime';
export const DEV_SURIMI_PACKAGE_PATTERN = 'packages/surimi/';
export const DEV_PARSERS_PACKAGE_PATTERN = 'packages/parsers/';

// Watch mode configuration
export const WATCH_BUILD_DELAY = 100;
