import path from 'node:path';
import { createFilter } from '@rollup/pluginutils';
import compile from '@surimi/compiler';
import fastGlob from 'fast-glob';
import type { Plugin, ResolvedConfig, ViteDevServer } from 'vite';
import { normalizePath } from 'vite';

import type { SurimiOptions } from './types.js';

export default function surimi(options: SurimiOptions = {}): Plugin {
  const { include = ['**/*.css.{ts,js}'], exclude = ['node_modules/**', '**/*.d.ts'] } = options;

  const filter = createFilter(include, exclude);

  let resolvedConfig: ResolvedConfig | undefined;

  const compiledFiles = new Map<string, { css: string; cssFileId: string }>();

  return {
    name: 'vite-plugin-surimi',
    configResolved(config) {
      resolvedConfig = config;
    },
    async load(id) {
      if (filter(id)) {
        console.log('Processing Surimi file:', id);

        try {
          // Compile the CSS-in-JS file
          const css = await compile({
            inputPath: normalizePath(id),
            cwd: resolvedConfig?.root ?? process.cwd(),
            include,
            exclude,
          });

          console.log('Compiled CSS:', css);

          // Generate a unique CSS filename - handle .css.ts files correctly
          const parsedPath = path.parse(id);
          const baseName = parsedPath.name.replace(/\.css$/, ''); // Remove .css if present
          const cssFileName = `${baseName}.css`;

          // Emit the CSS as an asset
          const cssFileId = this.emitFile({
            type: 'asset',
            fileName: cssFileName,
            source: css,
          });

          // Store the compilation result
          compiledFiles.set(id, { css, cssFileId });

          // Return JavaScript that imports the CSS
          // The CSS will be injected automatically by Vite when imported
          const jsCode = `
// Auto-generated by vite-plugin-surimi
// Import the generated CSS file - Vite will handle injection
import "./${cssFileName}";

// Export any tokens/class names if needed (placeholder for now)
export default {};
`;

          return jsCode;
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          this.error(`Failed to compile Surimi file ${id}: ${message}`);
        }
      }

      return null;
    },
    generateBundle() {
      // Ensure all CSS files are properly emitted
      console.log('Generated CSS files:', Array.from(compiledFiles.keys()));
    },
  };
}
